gateway:
  host: 0.0.0.0
  port: 7004


database:
  dsn: "host=localhost port=5432 user=root password=secret dbname=tsarka sslmode=disable statement_cache_mode=describe"

pgxpool:
  max_conn_lifetime: 3600 # seconds
  max_conn_idle_time: 1800 # seconds
  min_conns: 0
  max_conns: 2